apiVersion: v1
kind: Service
metadata:
  name: {{ include "wasup-worker.fullname" . }}
  labels:
    {{- include "wasup-worker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "wasup-worker.name" . }}
    wasup.ai/instance-id: {{ .Values.instanceId | quote }}
